### ISSUE TITLE
Michiel Trimpe

### ISSUE THREAD

**Issue by mtrimpe** [enbytech/enbytech.github.io#12]
# Please, add me to the list!

**Your Name**: Michiel Trimpe

**Link to your twitter/github/website/whatever**: https://twitter.com/mtrimpe

**Your favourite emoji**:

**Comment by Charlotteis** [comment]
Hi there!

You're now in the list.

Please feel free to open a new issue to update your Location and Talk topics, or make a PR!

Thanks 🌸
