### ISSUE TITLE
Enby speaker

### ISSUE THREAD

**Issue by makyo** [enbytech/enbytech.github.io#14]
# Please, add me to the list!

**Your Name**: Madison Scott-Clary

**Link to your twitter/github/website/whatever**: http://drab-makyo.com

**Your favourite emoji**: Emoji? 🤔 Kaomoji: ¯\_(ツ)_/¯

PS - This is such a fantastic idea!

**Comment by Charlotteis** [comment]
Hi there!

You're now in the list.

Please feel free to open a new issue to update your Location and Talk topics, or make a PR!

Thanks 🌸
