### ISSUE TITLE
Kieryn Darkwater

### ISSUE THREAD

**Issue by kiery** [enbytech/enbytech.github.io#15]
# Please, add me to the list!

**Your Name**: Kieryn Darkwater

**Link to your twitter/github/website/whatever**: @mxdarkwater, mxdarkwater.com, GitHub.com/kiery

**Your favourite emoji**: 💙

**Comment by Charlotteis** [comment]
Hi there!

You're now in the list.

Please feel free to open a new issue to update your Location and Talk topics, or make a PR!

Thanks 🌸
