### ISSUE TITLE
Please, add me to the list!

### ISSUE THREAD

**Issue by alphabetica** [enbytech/enbytech.github.io#16]
# Please, add me to the list!

**Your Name**: Katja Bak

**Link to your twitter/github/website/whatever**: https://medium.com/@katja_ghost

**Your favourite emoji**: 🌿

**Comment by Charlotteis** [comment]
Hi there!

You're now on the list.

Please feel free to open a new issue to update your Location and Talk topics, or make a PR!

Thanks 🌸
