### ISSUE TITLE
Please add Cory Kolbeck to speakers list

### ISSUE THREAD

**Issue by ckolbeck** [enbytech/enbytech.github.io#17]
# Please, add me to the list!

**Your Name**:
Cory 'cbeck' Kolbeck

**Link to your twitter/github/website/whatever**:
https://twitter.com/cbeckpdx

**Your favourite emoji**:
:heart_eyes_cat:

**Comment by Charlotteis** [comment]
Hi there!

You're now on the list.

Please feel free to open a new issue to update your Location and Talk topics, or make a PR!

Thanks 🌸

**Comment by ckolbeck** [comment]
Thank you <3

**Comment by Charlotteis** [comment]
no, u <3
