### ISSUE TITLE
Add me too 🙋

### ISSUE THREAD

**Issue by katemihalikova** [enbytech/enbytech.github.io#20]
Hi there Charlotte, please, add me to the list too!

**Your Name**: Kate Miháliková 

**Link to your twitter/github/website/whatever**: twitter.com/KateMihalikova & katemihalikova.cz (@katem on wealljs) 

**Your favourite emoji**: 😂

**Comment by katemihalikova** [comment]
**Location (optional)**: Prague, 🇨🇿

**Talk Topic(s) (optional)**:
- introduction into HTML, CSS or Javascript
- Javascript in general
- Angular
- Ionic

**Comment by Charlotteis** [comment]
Thanks Kate! You're on the site now. 🌸
