### ISSUE TITLE
Samathy

### ISSUE THREAD

**Issue by Charlotteis** [enbytech/enbytech.github.io#23]
# Please, add me to the list!

**Your Name**: Samathy Barratt

**Link to your twitter/github/website/whatever**: https://twitter.com/Samathy_Barratt

**Comment by Samathy** [comment]
Github.com/samathy
sbarratt.co.uk
samathy@sbarratt.co.uk

<3

**Comment by Charlotteis** [comment]
I finally added you! Please feel free to send a PR adding your location and talk topics 👍
