### ISSUE TITLE
Add pris to enbytech

### ISSUE THREAD

**Issue by pnasrat** [enbytech/enbytech.github.io#33]
closing out

**Comment by Charlotteis** [comment]
Hi @pnasrat.

Shall I assume you don't want me to put you on the list?

Sorry for the delay. I've been taking a break over the Christmas period to recharge.

Please let me know if something else made you close this.

Best,
Charlotte

**Comment by pnasrat** [comment]
Correct (various life reasons)

**Comment by Charlotteis** [comment]
Okay. Good luck with everything :)
