### ISSUE TITLE
add new speaker

### ISSUE THREAD

**Issue by SekhmetDesign** [enbytech/enbytech.github.io#39]
# Please, add me to the list!

**Your Name**: Debbie Rouleau

**Link to your twitter/github/website/whatever**: 
blog: [http://sekhmetdesign.com/](http://sekhmetdesign.com/) 
twitter: [https://twitter.com/SekhmetDesign](https://twitter.com/SekhmetDesign)

**Comment by Charlotteis** [comment]
Added! Feel free to add location and talk topics.
