### ISSUE TITLE
Add Erik

### ISSUE THREAD

**Issue by erikr** [enbytech/enbytech.github.io#68]
# Please, add me to the list!

**Your Name**:
Erik Romijn

**Link to your twitter/github/website/whatever**:
https://twitter.com/erikpub

**Location (optional)**:
Amsterdam, The Netherlands

**Talk Topic(s) (optional)**:
Communities, well-being and mental health, empathy, Django, code of conduct, inclusivity, ethics.

**Your favourite emoji**:
🐿

**Comment by Charlotteis** [comment]
done! good luck at the talk :)
