### ISSUE TITLE
add igor to the list

### ISSUE THREAD

**Issue by igalic** [enbytech/enbytech.github.io#9]
# Please, add me to the list!

**My Name**: is Igor Galić

**Link to my**:
twitter: [@hirojin](https://twitter.com/hirjin)
github: @igalic
"blog": https://blag.esotericsystems.at/
whatever: ¯\\(°_o)/¯

**My favourite emoji**: 😓

**stuff i talk about**: Dev/Ops things. Open Source things.

**Comment by Charlotteis** [comment]
You are on there now! :) Thanks!
